language: generic
before_install:
    - echo "Before running"
    
script: 
    - echo "Running..."
    - python resume_to_html/retriever.py
    
after_success:
    - echo "Successfully ran the script!"